name: "GitHub Followers Tracker"

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */2 * * *"

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'

    - name: Install NPM dependancies
      run: npm install

    - name: Run code
      run: node index
      env:
        GIST_ID: ${{ secrets.GIST_ID }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        TG_BOT_NAME: ${{ secrets.TG_BOT_NAME }}
        TG_BOT_SECRET: ${{ secrets.TG_BOT_SECRET }}
